### PR TITLE
ID-189 Remove W from header when printing non-branded sites

### PR DESCRIPTION
**Pull request by acursley**
Tiny fix.

### CODE REVIEW

**Comment by matmannion** [comment]
LGTM

**Comment by halfninja** [comment]
Will need a separate SB issue to deal with porting this across

**Comment by matmannion** [comment]
SB will just get it with the next bower update, which I'll do the next time there's a release

**Comment by halfninja** [comment]
Sorry, meant that to be about the change to the homepage HTML

**Pull request merged**
