### PR TITLE
ID-93 - Re-apply patch removed by upgrade to BS 3.3.7

### PR DESCRIPTION
**Pull request by flamingelk**

### CODE REVIEW

**Comment by halfninja** [comment]
It was Mat who did the subsequent upgrade so if it's not visible to the original author of the patch, we should probably add something visible in bower.json to warn people of the dangers

**Comment by nanoamp** [comment]
There's also instructions for making releases in RELEASES.md; worth a note there.

**Comment by halfninja** [comment]
Alternative is to put the patch properly into a branch of a fork of bootstrap, and change the bower dependency to that. Bit more work, but makes it a lot harder to regress

**Comment by matmannion** [comment]
Famous last words but it's not massively important as I don't expect there'll be any more Bootstrap 3.x releases.

**Pull request merged**
