### PR TITLE
ID-388 Turned dreadful font awesome triangle into amazing CSS triangle

### PR DESCRIPTION
**Pull request by WarwickGoatee**
Tested on major browsers and IE11.

### CODE REVIEW

**Comment by lol768** [comment]
c.f. https://deploy-preview-241--id7.netlify.app/examples/subsite-homepage/

https://id7.warwick.ac.uk/examples/subsite-homepage/

**Comment by lol768** [comment]
Screenshot from 2020-10-08 13-18-29

In Firefox, this is slightly closer to parity and reduces the horizontal shift of the text after the arrow.

**Comment by matmannion** [comment]
Maybe want it in rems so it scales with font size?

**Comment by WarwickGoatee** [comment]
> Screenshot from 2020-10-08 13-18-29
> 
> In Firefox, this is slightly closer to parity and reduces the horizontal shift of the text after the arrow.

Do we really want to start faffing around with half pixels/percentages? Not sure the original triangle was so utterly perfect it needs to be replicated exactly...

**Comment by WarwickGoatee** [comment]
Updated

**Review by lol768 — APPROVED** [review]

**Pull request merged**
