### PR TITLE
Fix megamenu links scrolling

### PR DESCRIPTION
**Pull request by lol768**
Tested in Edge, IE11, Safari, Firefox and Chrome. As discussed, we should ensure that there wasn't a historical reason this wasn't already done before merging.

### CODE REVIEW

**Comment by nanoamp** [comment]
Tested on tablet (ie. >xs) renditions?

**Comment by lol768** [comment]
bs_realios_tablet_ipad pro-11 0

iPad seems to work

**Comment by lol768** [comment]
fwiw @matmannion this appears to have regressed in hp-2019

**Comment by matmannion** [comment]
@lol768 I just blanket copied a bunch of the styling for hp-2019, but I think it'd be correct to undo the position: fixed - thanks for spotting

**Pull request merged**
