### PR TITLE
v2.9.0

### PR DESCRIPTION
**Pull request by joshdavies14**
- Fix MyWarwick popover click-to-dismiss not working (ID-399)
- Add borderless support (ID-395)
- Use loadCSS for loading fonts (SBTWO-9622)

### CODE REVIEW

**Comment by lol768** [comment]
As the compiled assets are in the repository (for historical reasons) you may need to do a build with npm and commit the changed assets

**Comment by halfninja** [comment]
> As the compiled assets are in the repository (for historical reasons) you may need to do a build with npm and commit the changed assets

The build runs on prepublish so it will happen whenever the package is published to NPM - and I think a GitHub Action manages building and packaging a dist release. Not sure we still need the `dist` folder in the repo

**Comment by lol768** [comment]
> The build runs on prepublish so it will happen whenever the package is published to NPM - and I think a GitHub Action manages building and packaging a dist release

Agreed.

> Not sure we still need the dist folder in the repo

Let's can it then - Josh can you `git rm -r` it

**Comment by joshdavies14** [comment]
`dist` folder has been removed!

**Review by lol768 — APPROVED** [review]

**Pull request merged**
