### PR TITLE
Upgrade ID7 to Font Awesome 5

### PR DESCRIPTION
**Pull request by halfninja**
Has been used and tested a bit.

We have noticed some issues with the navigation (CASE-155) which may need resolving here first.

### CODE REVIEW

**Comment by flamingelk** [comment]
As the Bamboo build is failing for this branch I think this needs a build of the generated assets committing by hand.

**Comment by halfninja** [comment]
I'd prefer to sort out a working Bamboo build instead, we'll need to do it anyway

**Comment by halfninja** [comment]
Considering whether to remove the FA4 shims from the standard build - most apps should be fully upgrading and won't need this extra guff; we only really need it for the main website with its large corpus of user content referencing FA4 icons.

**Comment by matmannion** [comment]
I’m fine with removing the shims and having them be opt-in for Sitebuilder

**Pull request merged**
