### PR TITLE
Bump to version 2.4.3 in preparation for release

### PR DESCRIPTION
**Pull request by lol768**
# Release Notes - Brand - Version 2.4.3
                                    
<h2>        Bug
</h2>
<ul>
<li>[<a href='https://bugs.elab.warwick.ac.uk/browse/ID-325'>ID-325</a>] -         event listener for non-safari browsers on mac does not work reliably
</li>
</ul>

### CODE REVIEW

**Comment by lk9100** [comment]
:shipit:

**Comment by lol768** [comment]
This appears to have regressed double scrolling in supporting browsers.

C.f. https://deploy-preview-149--id7.netlify.com/components/main-content/ (a week ago) with https://deploy-preview-159--id7.netlify.com/components/main-content/ (this PR)

In Firefox I see double scrollbars as expected on the former URL, but not on the latter.

**Comment by lol768** [comment]
@lk9100 can you take a look and see if your change has impacted this?

**Comment by lk9100** [comment]
> @lk9100 can you take a look and see if your change has impacted this?

@lol768 👀

**Comment by lk9100** [comment]
@lol768 good catch, i've pushed a commit to address this

**Comment by lol768** [comment]
For the record, we had a chat in-person about this and think we've isolated the reason for the behaviour applying to Firefox on Linux.

**Comment by lol768** [comment]
>@lol768 good catch, i've pushed a commit to address this

Can confirm [the page](https://deploy-preview-159--id7.netlify.com/components/main-content/) we discussed now works as intended with Firefox. Does it still work fine on macOS @lk9100?

**Comment by lk9100** [comment]
let me double check on that @lol768

**Comment by lk9100** [comment]
after testing we verified this is broken, and 2.4.3 is also broken, i will update this release branch to basically put thing back to 2.4.1

basically ID7 is the wrong place to do this, as pure ID7 does not suffer the issue which tabula has. tabula modified doublescroll in some ways hence the strange behaviour in tabula.

sorry for wasting everyone's time :(

**Comment by lk9100** [comment]
:cone-of-shame:

**Comment by lol768** [comment]
I'll wait for the deploy preview, then merge this :smile: 

We should ensure the broken versions are marked as such. Is it just 2.4.2? Is 2.4.1 fine?

**Comment by lk9100** [comment]
> I'll wait for the deploy preview, then merge this 😄
> 
> We should ensure the broken versions are marked as such. Is it just 2.4.2? Is 2.4.1 fine?

yes 2.4.1 is fine

**Pull request merged**
